"""empty message

Revision ID: 55cd60c9cac8
Revises: 9090a10ae830
Create Date: 2022-09-08 16:16:06.302976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55cd60c9cac8'
down_revision = '9090a10ae830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=200), nullable=False))
    op.create_index('email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
